// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseUsageMetadata } from "./ResponseUsageMetadata";
import type { ThreadTokenUsageAttribution } from "./ThreadTokenUsageAttribution";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

/**
 * Internal-only notification containing the exact usage from one upstream
 * Responses API completion.
 */
export type RawResponseCompletedNotification = { threadId: string, turnId: string, responseId: string, usage: TokenUsageBreakdown | null, usageMetadata: ResponseUsageMetadata | null,
/**
 * Originating thread for forwarded one-shot child responses. Usually equal to `thread_id`.
 */
sourceThreadId: string | null,
/**
 * Parent of the originating thread, when the response came from a child agent.
 */
parentThreadId: string | null,
/**
 * Unix timestamp in seconds when the response completed.
 */
completedAt: bigint | null,
/**
 * Source metadata captured with the exact response usage.
 */
attribution: ThreadTokenUsageAttribution | null, };
