// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Process-local lifecycle phase for a shared app-server daemon.
 *
 * `Draining` means the server has begun a graceful restart and will reject
 * new work admission while existing assistant turns drain. `Forced` means a
 * second forceable shutdown signal arrived; the server may terminate before
 * all work completes. Neither phase is a durable thread checkpoint.
 */
export type ServerLifecyclePhase = "ready" | "draining" | "forced";
