// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerLifecyclePhase } from "./ServerLifecyclePhase";

/**
 * Emitted when the process lifecycle phase or draining turn count changes.
 */
export type ServerLifecycleUpdatedNotification = {
/**
 * UUID generated for this app-server process. It changes after restart.
 */
daemonInstanceId: string, phase: ServerLifecyclePhase,
/**
 * UUID shared by lifecycle updates for one graceful drain attempt.
 * It is absent while the process is ready.
 */
transitionId: string | null,
/**
 * Number of assistant turns currently reported as running by this process.
 */
runningAssistantTurns: number, };
