// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capabilities exposed by the host for non-model slash commands.
 */
export type SlashCommandCapabilities = { status: boolean, spend: boolean, reload: boolean, };
