// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "../RequestId";
import type { SlashCommandResultPayload } from "./SlashCommandResultPayload";

/**
 * Non-model output generated by a slash command.
 */
export type SlashCommandResultNotification = { threadId: string, command: string, requestId: RequestId, result: SlashCommandResultPayload, };
