// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlashCommandOutput } from "./SlashCommandOutput";
import type { SlashCommandReloadResult } from "./SlashCommandReloadResult";
import type { SlashCommandResultKind } from "./SlashCommandResultKind";

/**
 * Payload carried by the asynchronous slash-command result notification.
 *
 * This intentionally has its own schema name instead of reusing
 * [`SlashCommandExecuteResponse`].  The app-server schema exporter emits
 * response types and notification payloads as independent roots; nesting the
 * response root in the notification causes a duplicate v2 definition.
 */
export type SlashCommandResultPayload = { command: string, ok: boolean, resultKind: SlashCommandResultKind, output: SlashCommandOutput, reload?: SlashCommandReloadResult, };
