// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A host-provided slash command available to an app-server client.
 */
export type SlashCommandSpec = { name: string, aliases?: Array<string>, description: string, supportsInlineArgs: boolean, available: boolean, unavailableReason?: string, };
