// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SwitchAccountParams = {
/**
 * Managed account alias to activate. `null` means use the original root auth store.
 */
alias?: string | null, };
