// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";

/**
 * Persisted root-session metadata attached to a task in the cross-session ETA navigator.
 */
export type ThreadEtaSessionInfo = {
/**
 * Root thread id to pass to `thread/resume`.
 */
threadId: string, title: string, name: string | null, preview: string | null, createdAt: bigint, updatedAt: bigint, archivedAt: bigint | null, cwd: LegacyAppPathString, };
