// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadHandoffBlocker = "unsupportedTask" | "activeOperation" | "pendingApproval" | "pendingUserInput" | "pendingDynamicToolResponse" | "pendingInput" | "pendingMailbox" | "pendingDispatch" | "unifiedExecProcess" | "liveDescendants" | "persistence" | "versionMismatch" | "parentUnavailable" | "realtimeConversation" | "suspensionTimeout" | "taskExitedUnexpectedly" | "turnFinalization";
