// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - emitted with the remote SDP for a WebRTC realtime session.
 */
export type ThreadRealtimeSdpNotification = { threadId: string,
/**
 * Stable submission identifier shared by all notifications from this realtime session.
 */
submissionId?: string, sdp: string, };
