// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client settings for configuring per-thread usage-limit behavior.
 */
export type ThreadUsagePolicyParams = {
/**
 * Retry a resettable provider usage limit after its authoritative reset time.
 */
autoResume?: boolean | null,
/**
 * Stop harness-driven continuation when a known provider window has less than this much
 * usage remaining. Explicit user turns are not blocked by this floor. Omit
 * the field to preserve its current value; pass `null` to clear the floor.
 */
minimumRemainingPercent?: number | null, };
