// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadEtaAccuracy } from "./ThreadEtaAccuracy";
import type { ThreadEtaRevision } from "./ThreadEtaRevision";
import type { ThreadEtaStatus } from "./ThreadEtaStatus";

/**
 * A task in the root session's active tree or bounded history page.
 */
export type ThreadEtaTask = { taskId: string, rootThreadId: string, ownerThreadId: string, parentTaskId: string | null, dependsOnTaskIds: Array<string>, title: string, status: ThreadEtaStatus,
/**
 * Remaining duration range for active work; terminal rows retain their last range.
 */
currentLowerSeconds: bigint | null, currentUpperSeconds: bigint | null, originalLowerSeconds: bigint | null, originalUpperSeconds: bigint | null, createdAt: bigint, startedAt: bigint | null, terminalAt: bigint | null, actualElapsedSeconds: bigint | null, updatedAt: bigint, isStale: boolean, accuracy: ThreadEtaAccuracy, revisions: Array<ThreadEtaRevision>, };
