// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Process-local manual pause state for a loaded thread.
 */
export type ThreadPauseState = "running" | "pausing" | "paused";
