// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { TeamMode } from "../TeamMode";
import type { TeamRole } from "../TeamRole";

/**
 * Effective team state returned in thread settings.
 */
export type ThreadTeamSettings = { mode: TeamMode, role: TeamRole | null, leadModel: string | null, leadReasoningEffort: ReasoningEffort | null, leadBalance: number | null, workerModel: string | null, workerReasoningEffort: ReasoningEffort | null, previousModel: string | null, previousReasoningEffort: ReasoningEffort | null, };
