// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accuracy classification against a task's immutable original estimate.
 */
export type ThreadEtaAccuracy = "early" | "within" | "late" | "unknown";
