// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source metadata captured with one exact upstream response.
 */
export type ThreadTokenUsageAttribution = { model: string | null, modelProvider: string | null, serviceTier: string | null, contextLength: string | null, };
