// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { TeamMode } from "../TeamMode";
import type { TeamRole } from "../TeamRole";

/**
 * Team mode or profile patch accepted by `thread/settings/update`.
 *
 * When `role`, `model`, and `reasoning_effort` are supplied, the selected
 * profile is changed for this thread only. The server preserves the other
 * profile and the role assignment captured by the thread snapshot.
 */
export type ThreadTeamSettingsUpdate = { mode: TeamMode, role?: TeamRole | null, model?: string | null, reasoningEffort?: ReasoningEffort | null, };
