// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamMode } from "../TeamMode";

/**
 * Team mode accepted by `thread/settings/update`.
 */
export type ThreadTeamSettingsUpdate = { mode: TeamMode, };
