// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-thread controls for continuing work near or after provider usage limits.
 * Auto-resume waits only while the rejected turn remains active in the current
 * process; the policy itself persists for later turns and future resumes.
 */
export type ThreadUsagePolicy = {
/**
 * Retry a resettable provider usage limit after its authoritative reset time.
 */
autoResume: boolean,
/**
 * Stop harness-driven continuation when a known provider window has less than this much
 * usage remaining. Explicit user turns are not blocked by this floor.
 */
minimumRemainingPercent: number | null, };
