// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bounded estimate revision retained for a task.
 */
export type ThreadEtaRevision = { lowerSeconds: bigint | null, upperSeconds: bigint | null, reason: string | null, updatedAt: bigint, actorThreadId: string, };
