// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadEtaOverall } from "./ThreadEtaOverall";
import type { ThreadEtaTask } from "./ThreadEtaTask";

/**
 * Read-only root-scoped ETA projection returned by `thread/eta/read`.
 */
export type ThreadEtaSnapshot = { rootThreadId: string, generatedAt: bigint, sequence: bigint, active: Array<ThreadEtaTask>, history: Array<ThreadEtaTask>, nextCursor: string | null, overall: ThreadEtaOverall, };
