// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state for a task tracked by the ETA store.
 */
export type ThreadEtaStatus = "pending" | "active" | "blocked" | "completed" | "cancelled" | "unknown";
