// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTokenUsageAttribution } from "./ThreadTokenUsageAttribution";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

/**
 * Cumulative exact usage for one model/provider/service-tier/context source. This is sent only as
 * part of restored thread usage so clients can price mixed-model histories without replaying every
 * response record.
 */
export type ThreadTokenUsageSource = { threadId: string, attribution: ThreadTokenUsageAttribution, responseIds: Array<string>, usage: TokenUsageBreakdown, };
