// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadEtaSessionInfo } from "./ThreadEtaSessionInfo";
import type { ThreadEtaStatus } from "./ThreadEtaStatus";

/**
 * A lightweight task-first row spanning persisted ETA roots.
 */
export type ThreadEtaSessionTask = { taskId: string, rootThreadId: string, ownerThreadId: string, parentTaskId: string | null, title: string, status: ThreadEtaStatus, currentLowerSeconds: bigint | null, currentUpperSeconds: bigint | null, originalLowerSeconds: bigint | null, originalUpperSeconds: bigint | null, createdAt: bigint, startedAt: bigint | null, terminalAt: bigint | null, actualElapsedSeconds: bigint | null, updatedAt: bigint,
/**
 * Whether this active row exceeded its root's persisted freshness window.
 */
isStale: boolean, session: ThreadEtaSessionInfo,
/**
 * Number of transitive child tasks, including terminal children retained in history.
 */
nestedTaskCount: number,
/**
 * Number of transitive child tasks that are not terminal.
 */
activeNestedTaskCount: number,
/**
 * Sum of remaining ranges for active transitive children; unknown when any active child is unknown.
 */
nestedLowerSeconds: bigint | null, nestedUpperSeconds: bigint | null, };
