// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadControlMode } from "./ThreadControlMode";

export type ThreadControl = { threadId: string, mode: ThreadControlMode, reason: string, releaseChannel: string | null, watchIntervalSeconds: number | null, releasedAt: number | null, updatedAt: number, targetThreadIds: Array<string>, };
