// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadHandoffNode } from "./ThreadHandoffNode";
import type { ThreadHandoffState } from "./ThreadHandoffState";

/**
 * Durable receipt for a process handoff.
 */
export type ThreadHandoffReceipt = { handoffId: string, state: ThreadHandoffState, runtimeVersion: string,
/**
 * Creation time as integer Unix seconds.
 */
createdAt: number, nodes: Array<ThreadHandoffNode>, };
