// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of one thread in a handoff receipt.
 */
export type ThreadHandoffNodeState = "planned" | "suspending" | "suspended" | "notActive" | "recovering" | "restored" | "paused" | "needsAttention";
