// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadHandoffBlocker } from "./ThreadHandoffBlocker";
import type { ThreadHandoffNodeState } from "./ThreadHandoffNodeState";

/**
 * Stable thread identity and process-local state captured for recovery.
 */
export type ThreadHandoffNode = { threadId: string, rootThreadId: string, parentThreadId: string | null, agentPath: string | null, turnId: string | null, rolloutPath: string | null, wasRunning: boolean, wasPaused: boolean, state: ThreadHandoffNodeState, blockers: Array<ThreadHandoffBlocker>, };
