// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadActivity } from "./ThreadActivity";
import type { ThreadActivityWaitReason } from "./ThreadActivityWaitReason";
import type { ThreadPauseState } from "./ThreadPauseState";

export type ThreadActivityState = { threadId: string, rootThreadId: string, activity: ThreadActivity, pauseState: ThreadPauseState, waitReason: ThreadActivityWaitReason | null, inFlightOperations: number, };
