// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPreferencesMemoryBucketPolicy } from "../UserPreferencesMemoryBucketPolicy";

export type ThreadUserPreferencesMemoryPolicySetParams = { threadId: string, policy: UserPreferencesMemoryBucketPolicy, };
