// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit operator resolution for an unresolved handoff receipt.
 */
export type ThreadHandoffRecoveryResolution = "retry" | "quarantine";
