// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a thread is waiting instead of actively executing.
 */
export type ThreadActivityWaitReason = "approval" | "userInput" | "usageLimit" | "agents";
