// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadExecPolicyParams = {
/**
 * Named exec-policy rulesets to apply to this thread.
 */
rulesets: Array<string>, };
