// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - emitted when thread realtime transport closes.
 */
export type ThreadRealtimeClosedNotification = { threadId: string,
/**
 * Stable submission identifier shared by all notifications from this realtime session.
 */
submissionId?: string, reason: string | null, };
