// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadEtaAction } from "./ThreadEtaAction";

/**
 * One requested ETA mutation. Fields omitted for an action are left unchanged;
 * `create` requires a title and may omit an estimate to record an explicit unknown.
 */
export type ThreadEtaUpdateOperation = { action: ThreadEtaAction, taskId: string | null, title: string | null, parentTaskId: string | null, dependsOnTaskIds: Array<string> | null, estimateLowerSeconds: bigint | null, estimateUpperSeconds: bigint | null, reason: string | null, ownerThreadId: string | null, };
