// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, usageByServiceTier: { [key in string]?: TokenUsageBreakdown }, usageByServiceTierAndContextLength: { [key in string]?: { [key in string]?: TokenUsageBreakdown } }, modelContextWindow: number | null, };
