// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadEtaOverall } from "./ThreadEtaOverall";
import type { ThreadEtaTask } from "./ThreadEtaTask";

/**
 * Event-driven update emitted after a task mutation. Clients should refresh the
 * read projection only when this sequence is newer than their local snapshot.
 */
export type ThreadEtaUpdatedNotification = { rootThreadId: string, generatedAt: bigint, sequence: bigint, changedTasks: Array<ThreadEtaTask>, overall: ThreadEtaOverall, };
