// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mutation operation accepted by `thread/eta/update` and the model-facing ETA tool.
 */
export type ThreadEtaAction = "create" | "start" | "revise" | "block" | "complete" | "cancel";
