// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTokenUsageProjection } from "./ThreadTokenUsageProjection";

/**
 * Complete billing usage reconstructed from persisted response records.
 *
 * This notification is sent independently from the context-window counters in
 * [`ThreadTokenUsageUpdatedNotification`]. A missing projection means the server could not read
 * the complete history; an empty projection is a complete zero-usage baseline.
 */
export type ThreadTokenUsageProjectionUpdatedNotification = { threadId: string, usageProjection: ThreadTokenUsageProjection | null, };
