// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnScratchpadUpdatedNotification = { threadId: string, turnId: string, scratchpadId: string, objective: string, status: string, completed: Array<string>, nextSteps: Array<string>, pendingWaits: Array<string>, updatedAt: string, archivedAt: string | null, };
