// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects whether a thread uses its configured Lead/Worker model assignments.
 */
export type TeamMode = "off" | "leadWorker";
