// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Role and assignments captured with a thread's durable team setting.
 */
export type TeamRole = "lead" | "worker";
