// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPreferencesMemoryBucket = "durable_preference" | "personal_context" | "relational_attunement" | "operator_playbook" | "ongoing_threads" | "followup_state";
