use crate::JsonSchema;
use crate::RequestId;
use crate::TS;
use serde::{Deserialize, Serialize};

/// A host-provided slash command available to an app-server client.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandSpec {
    pub name: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub aliases: Vec<String>,
    pub description: String,
    #[serde(default)]
    pub supports_inline_args: bool,
    pub available: bool,
    #[ts(optional)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unavailable_reason: Option<String>,
}

/// Capabilities exposed by the host for non-model slash commands.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandCapabilities {
    pub status: bool,
    pub spend: bool,
    pub reload: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandListParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
    #[serde(default)]
    pub side_conversation: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandListResponse {
    pub commands: Vec<SlashCommandSpec>,
    pub capabilities: SlashCommandCapabilities,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandExecuteParams {
    pub thread_id: String,
    pub command: String,
    #[serde(default)]
    pub args: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub enum SlashCommandResultKind {
    Status,
    Spend,
    Reload,
    Text,
    Error,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandOutput {
    pub format: String,
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandReloadResult {
    pub eligible: bool,
    pub state: String,
    #[ts(optional)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandExecuteResponse {
    pub command: String,
    pub ok: bool,
    pub result_kind: SlashCommandResultKind,
    pub output: SlashCommandOutput,
    #[ts(optional)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reload: Option<SlashCommandReloadResult>,
}

/// Payload carried by the asynchronous slash-command result notification.
///
/// This intentionally has its own schema name instead of reusing
/// [`SlashCommandExecuteResponse`].  The app-server schema exporter emits
/// response types and notification payloads as independent roots; nesting the
/// response root in the notification causes a duplicate v2 definition.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandResultPayload {
    pub command: String,
    pub ok: bool,
    pub result_kind: SlashCommandResultKind,
    pub output: SlashCommandOutput,
    #[ts(optional)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reload: Option<SlashCommandReloadResult>,
}

/// Non-model output generated by a slash command.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub struct SlashCommandResultNotification {
    pub thread_id: String,
    pub command: String,
    pub request_id: RequestId,
    pub result: SlashCommandResultPayload,
}
